FROM ubuntu

RUN apt-get update && \
    apt-get install -y apt-transport-https && \
    apt-get insatll docker.io
# apt-get install -y build-essential ca-certificates wget gcc g++ && rm -rf /var/lib/apt/lists/* && \
# apt search vim && apt install vim && vim --version && \

WORKDIR github.com/kadensungbincho/apache-ranger-docker-poc
COPY . .
RUN docker network create ranger-env && \
    cd docker-composes/ranger && \
    docker-compose up -d --build && \
    cd ../hadoop && \
    docker-compose up -d --build

WORKDIR github.com/big-data-europe/docker-hadoop
COPY . .
RUN docker-compose up

ENTRYPOINT ["bash"]
